//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototypeWithAuth.Models.LocationModels {
    using System;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    public class drawer {
        
        [Key()]
        public int drawerID { get; set; } //;
        
        [Required()]
        public int freezerID { get; set; } //;
        
        public freezer freezer { get; set; } //;
    }
}
