// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrototypeWithAuth.Data;

namespace PrototypeWithAuth.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200430070849_LocationInstanceSelfRefFK")]
    partial class LocationInstanceSelfRefFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PrototypeWithAuth.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("ApplicationUserID");

                    b.HasIndex("RequestID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.CompanyAccount", b =>
                {
                    b.Property<int>("CompanyAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyAccountNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("CompanyBankNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyBranchNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentTypeID")
                        .HasColumnType("int");

                    b.HasKey("CompanyAccountID");

                    b.HasIndex("PaymentTypeID");

                    b.ToTable("CompanyAccounts");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.LocationInstance", b =>
                {
                    b.Property<int>("LocationInstanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LocationInstanceParentID")
                        .HasColumnType("int");

                    b.Property<int>("LocationTypeID")
                        .HasColumnType("int");

                    b.HasKey("LocationInstanceID");

                    b.HasIndex("LocationInstanceParentID");

                    b.HasIndex("LocationTypeID");

                    b.ToTable("LocationInstances");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.LocationType", b =>
                {
                    b.Property<int>("LocationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<int?>("LocationTypeChildID")
                        .HasColumnType("int");

                    b.Property<string>("LocationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationTypeParentID")
                        .HasColumnType("int");

                    b.HasKey("LocationTypeID");

                    b.HasIndex("LocationTypeChildID");

                    b.HasIndex("LocationTypeParentID");

                    b.ToTable("LocationTypes");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.ParentCategory", b =>
                {
                    b.Property<int>("ParentCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ParentCategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParentCategoryID");

                    b.ToTable("ParentCategories");

                    b.HasData(
                        new
                        {
                            ParentCategoryID = 1,
                            ParentCategoryDescription = "Plastics"
                        },
                        new
                        {
                            ParentCategoryID = 2,
                            ParentCategoryDescription = "Reagents"
                        },
                        new
                        {
                            ParentCategoryID = 3,
                            ParentCategoryDescription = "Proprietry"
                        },
                        new
                        {
                            ParentCategoryID = 4,
                            ParentCategoryDescription = "Reusable"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.ParentRequest", b =>
                {
                    b.Property<int>("ParentRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<long>("Installments")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Payed")
                        .HasColumnType("bit");

                    b.Property<bool>("WithOrder")
                        .HasColumnType("bit");

                    b.HasKey("ParentRequestID");

                    b.HasIndex("ApplicationUserID");

                    b.ToTable("ParentRequests");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyAccountID")
                        .HasColumnType("int");

                    b.Property<int>("ParentRequestID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentID");

                    b.HasIndex("CompanyAccountID");

                    b.HasIndex("ParentRequestID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaymentTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentTypeID");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Handeling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("ProductComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductMedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductSubcategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityPerUnit")
                        .HasColumnType("int");

                    b.Property<int?>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int?>("UnitsInOrder")
                        .HasColumnType("int");

                    b.Property<int?>("UnitsInStock")
                        .HasColumnType("int");

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("ProductSubcategoryID");

                    b.HasIndex("VendorID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.ProductSubcategory", b =>
                {
                    b.Property<int>("ProductSubcategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ParentCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProductSubcategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductSubcategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("ProductSubcategories");

                    b.HasData(
                        new
                        {
                            ProductSubcategoryID = 11,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "Tubes"
                        },
                        new
                        {
                            ProductSubcategoryID = 12,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "Pipets"
                        },
                        new
                        {
                            ProductSubcategoryID = 13,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "Tips"
                        },
                        new
                        {
                            ProductSubcategoryID = 14,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "Dishes"
                        },
                        new
                        {
                            ProductSubcategoryID = 15,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "Cell Culture Plates"
                        },
                        new
                        {
                            ProductSubcategoryID = 21,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Chemical Powder"
                        },
                        new
                        {
                            ProductSubcategoryID = 22,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "DNA Enzyme"
                        },
                        new
                        {
                            ProductSubcategoryID = 23,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Antibodies"
                        },
                        new
                        {
                            ProductSubcategoryID = 24,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Cell Media"
                        },
                        new
                        {
                            ProductSubcategoryID = 31,
                            ParentCategoryID = 3,
                            ProductSubcategoryDescription = "Virus"
                        },
                        new
                        {
                            ProductSubcategoryID = 32,
                            ParentCategoryID = 3,
                            ProductSubcategoryDescription = "Plasmid"
                        },
                        new
                        {
                            ProductSubcategoryID = 33,
                            ParentCategoryID = 3,
                            ProductSubcategoryDescription = "Primers"
                        },
                        new
                        {
                            ProductSubcategoryID = 41,
                            ParentCategoryID = 4,
                            ProductSubcategoryDescription = "Beaker"
                        },
                        new
                        {
                            ProductSubcategoryID = 42,
                            ParentCategoryID = 4,
                            ProductSubcategoryDescription = "Buckets"
                        },
                        new
                        {
                            ProductSubcategoryID = 43,
                            ParentCategoryID = 4,
                            ProductSubcategoryDescription = "Measuring Instruments"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Request", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AmountWithInLocation")
                        .HasColumnType("bigint");

                    b.Property<long?>("AmountWithOutLocation")
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CatalogNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<double>("ExchangeRate")
                        .HasColumnType("float");

                    b.Property<byte>("ExpectedSupplyDays")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("ParentRequestID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestStatusID")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubSubUnitTypeID")
                        .HasColumnType("int");

                    b.Property<long?>("SubSubunit")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubUnit")
                        .HasColumnType("bigint");

                    b.Property<int?>("SubUnitTypeID")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Unit")
                        .HasColumnType("bigint");

                    b.Property<int?>("UnitTypeID")
                        .HasColumnType("int");

                    b.Property<long>("UnitsInStock")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitsOrdered")
                        .HasColumnType("bigint");

                    b.Property<byte>("Warranty")
                        .HasColumnType("tinyint");

                    b.HasKey("RequestID");

                    b.HasIndex("ApplicationUserID");

                    b.HasIndex("ParentRequestID");

                    b.HasIndex("ProductID");

                    b.HasIndex("RequestStatusID");

                    b.HasIndex("SubSubUnitTypeID");

                    b.HasIndex("SubUnitTypeID");

                    b.HasIndex("UnitTypeID");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.RequestStatus", b =>
                {
                    b.Property<int>("RequestStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RequestStatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestStatusID");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            RequestStatusID = 1,
                            RequestStatusDescription = "New"
                        },
                        new
                        {
                            RequestStatusID = 2,
                            RequestStatusDescription = "Ordered"
                        },
                        new
                        {
                            RequestStatusID = 3,
                            RequestStatusDescription = "RecievedAndIsInventory"
                        },
                        new
                        {
                            RequestStatusID = 4,
                            RequestStatusDescription = "Partial"
                        },
                        new
                        {
                            RequestStatusID = 5,
                            RequestStatusDescription = "Clarify"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.UnitParentType", b =>
                {
                    b.Property<int>("UnitParentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UnitParentTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitParentTypeID");

                    b.ToTable("UnitParentTypes");

                    b.HasData(
                        new
                        {
                            UnitParentTypeID = 1,
                            UnitParentTypeDescription = "Units"
                        },
                        new
                        {
                            UnitParentTypeID = 2,
                            UnitParentTypeDescription = "Weight/Volume"
                        },
                        new
                        {
                            UnitParentTypeID = 3,
                            UnitParentTypeDescription = "Test"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.UnitType", b =>
                {
                    b.Property<int>("UnitTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UnitParentTypeID")
                        .HasColumnType("int");

                    b.Property<string>("UnitTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitTypeID");

                    b.HasIndex("UnitParentTypeID");

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            UnitTypeID = 1,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Bottle"
                        },
                        new
                        {
                            UnitTypeID = 2,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Box"
                        },
                        new
                        {
                            UnitTypeID = 3,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Pack"
                        },
                        new
                        {
                            UnitTypeID = 4,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Bag"
                        },
                        new
                        {
                            UnitTypeID = 5,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Unit"
                        },
                        new
                        {
                            UnitTypeID = 6,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Vial"
                        },
                        new
                        {
                            UnitTypeID = 7,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "Kg"
                        },
                        new
                        {
                            UnitTypeID = 8,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "gr"
                        },
                        new
                        {
                            UnitTypeID = 9,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "mg"
                        },
                        new
                        {
                            UnitTypeID = 10,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "ug"
                        },
                        new
                        {
                            UnitTypeID = 11,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "Liter"
                        },
                        new
                        {
                            UnitTypeID = 12,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "ml"
                        },
                        new
                        {
                            UnitTypeID = 13,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "ul"
                        },
                        new
                        {
                            UnitTypeID = 14,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "gal"
                        },
                        new
                        {
                            UnitTypeID = 15,
                            UnitParentTypeID = 3,
                            UnitTypeDescription = "rxhs"
                        },
                        new
                        {
                            UnitTypeID = 16,
                            UnitParentTypeID = 3,
                            UnitTypeDescription = "test"
                        },
                        new
                        {
                            UnitTypeID = 17,
                            UnitParentTypeID = 3,
                            UnitTypeDescription = "preps"
                        },
                        new
                        {
                            UnitTypeID = 18,
                            UnitParentTypeID = 3,
                            UnitTypeDescription = "assays"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Vendor", b =>
                {
                    b.Property<int>("VendorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("OrderEmail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorAccountNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorBIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorBank")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorBankBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.Property<string>("VendorBuisnessID")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)")
                        .HasMaxLength(9);

                    b.Property<string>("VendorCity")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorContactPhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorContactPhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorEnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorGoldAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorHeName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorStreet")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorSwift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorZip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorID");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Comment", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.CompanyAccount", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.LocationInstance", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.LocationInstance", "LocationInstanceParent")
                        .WithMany()
                        .HasForeignKey("LocationInstanceParentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.LocationType", "LocationType")
                        .WithMany()
                        .HasForeignKey("LocationTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.LocationType", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.LocationType", "LocationTypeChild")
                        .WithMany()
                        .HasForeignKey("LocationTypeChildID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.LocationType", "LocationTypeParent")
                        .WithMany()
                        .HasForeignKey("LocationTypeParentID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.ParentRequest", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("ParentRequests")
                        .HasForeignKey("ApplicationUserID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Payment", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.CompanyAccount", "CompanyAccount")
                        .WithMany()
                        .HasForeignKey("CompanyAccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Models.ParentRequest", "ParentRequest")
                        .WithMany("Payments")
                        .HasForeignKey("ParentRequestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Product", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.ProductSubcategory", "ProductSubcategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductSubcategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.ProductSubcategory", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.ParentCategory", "ParentCategory")
                        .WithMany("ProductSubcategories")
                        .HasForeignKey("ParentCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Request", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", "ApplicationUserReceiver")
                        .WithMany()
                        .HasForeignKey("ApplicationUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.ParentRequest", "ParentRequest")
                        .WithMany("Requests")
                        .HasForeignKey("ParentRequestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Models.Product", "Product")
                        .WithMany("Requests")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Models.RequestStatus", "RequestStatus")
                        .WithMany("Requests")
                        .HasForeignKey("RequestStatusID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.UnitType", "SubSubUnitType")
                        .WithMany()
                        .HasForeignKey("SubSubUnitTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.UnitType", "SubUnitType")
                        .WithMany()
                        .HasForeignKey("SubUnitTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.UnitType", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.UnitParentType", "UnitParentType")
                        .WithMany("UnitTypes")
                        .HasForeignKey("UnitParentTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
