// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrototypeWithAuth.Data;

namespace PrototypeWithAuth.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200630083522_addDateToBePaidToRequests")]
    partial class addDateToBePaidToRequests
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PrototypeWithAuth.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecureAppPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("ApplicationUserID");

                    b.HasIndex("RequestID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.CompanyAccount", b =>
                {
                    b.Property<int>("CompanyAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyAccountNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("CompanyBankNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyBranchNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentTypeID")
                        .HasColumnType("int");

                    b.HasKey("CompanyAccountID");

                    b.HasIndex("PaymentTypeID");

                    b.ToTable("CompanyAccounts");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.LocationInstance", b =>
                {
                    b.Property<int>("LocationInstanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyLocationNo")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsFull")
                        .HasColumnType("bit");

                    b.Property<string>("LocationInstanceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationInstanceParentID")
                        .HasColumnType("int");

                    b.Property<int>("LocationTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("LocationInstanceID");

                    b.HasIndex("LocationInstanceParentID");

                    b.HasIndex("LocationTypeID");

                    b.ToTable("LocationInstances");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.LocationType", b =>
                {
                    b.Property<int>("LocationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<int?>("LocationTypeChildID")
                        .HasColumnType("int");

                    b.Property<string>("LocationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationTypeParentID")
                        .HasColumnType("int");

                    b.HasKey("LocationTypeID");

                    b.HasIndex("LocationTypeChildID");

                    b.HasIndex("LocationTypeParentID");

                    b.ToTable("LocationTypes");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.ParentCategory", b =>
                {
                    b.Property<int>("ParentCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ParentCategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParentCategoryID");

                    b.ToTable("ParentCategories");

                    b.HasData(
                        new
                        {
                            ParentCategoryID = 1,
                            ParentCategoryDescription = "Plastics"
                        },
                        new
                        {
                            ParentCategoryID = 2,
                            ParentCategoryDescription = "Reagents"
                        },
                        new
                        {
                            ParentCategoryID = 3,
                            ParentCategoryDescription = "Proprietry"
                        },
                        new
                        {
                            ParentCategoryID = 4,
                            ParentCategoryDescription = "Reusable"
                        },
                        new
                        {
                            ParentCategoryID = 5,
                            ParentCategoryDescription = "Equipment"
                        },
                        new
                        {
                            ParentCategoryID = 6,
                            ParentCategoryDescription = "Operation"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.ParentRequest", b =>
                {
                    b.Property<int>("ParentRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<long>("Installments")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Payed")
                        .HasColumnType("bit");

                    b.Property<bool>("WithOrder")
                        .HasColumnType("bit");

                    b.HasKey("ParentRequestID");

                    b.HasIndex("ApplicationUserID");

                    b.ToTable("ParentRequests");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyAccountID")
                        .HasColumnType("int");

                    b.Property<int>("ParentRequestID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentID");

                    b.HasIndex("CompanyAccountID");

                    b.HasIndex("ParentRequestID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaymentTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentTypeID");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Handeling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductMedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductSubcategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityPerUnit")
                        .HasColumnType("int");

                    b.Property<int?>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int?>("UnitsInOrder")
                        .HasColumnType("int");

                    b.Property<int?>("UnitsInStock")
                        .HasColumnType("int");

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("ProductSubcategoryID");

                    b.HasIndex("VendorID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.ProductSubcategory", b =>
                {
                    b.Property<int>("ProductSubcategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ParentCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProductSubcategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductSubcategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("ProductSubcategories");

                    b.HasData(
                        new
                        {
                            ProductSubcategoryID = 101,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "3D Cells Grow"
                        },
                        new
                        {
                            ProductSubcategoryID = 102,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "PCR Plates"
                        },
                        new
                        {
                            ProductSubcategoryID = 103,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "Blood"
                        },
                        new
                        {
                            ProductSubcategoryID = 104,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "Cell Culture Plates"
                        },
                        new
                        {
                            ProductSubcategoryID = 105,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "Dishes"
                        },
                        new
                        {
                            ProductSubcategoryID = 106,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "Tips"
                        },
                        new
                        {
                            ProductSubcategoryID = 107,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "Pipets"
                        },
                        new
                        {
                            ProductSubcategoryID = 108,
                            ParentCategoryID = 1,
                            ProductSubcategoryDescription = "Tubes"
                        },
                        new
                        {
                            ProductSubcategoryID = 201,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Chemical Powder"
                        },
                        new
                        {
                            ProductSubcategoryID = 202,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "DNA Enzyme"
                        },
                        new
                        {
                            ProductSubcategoryID = 203,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Antibodies"
                        },
                        new
                        {
                            ProductSubcategoryID = 204,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Cell Media"
                        },
                        new
                        {
                            ProductSubcategoryID = 205,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Chemicals Solution"
                        },
                        new
                        {
                            ProductSubcategoryID = 206,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Kit"
                        },
                        new
                        {
                            ProductSubcategoryID = 207,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "PCR"
                        },
                        new
                        {
                            ProductSubcategoryID = 208,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "ddPCR"
                        },
                        new
                        {
                            ProductSubcategoryID = 209,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "RT-PCR"
                        },
                        new
                        {
                            ProductSubcategoryID = 210,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Probes"
                        },
                        new
                        {
                            ProductSubcategoryID = 211,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Oligo"
                        },
                        new
                        {
                            ProductSubcategoryID = 212,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Media Supplement"
                        },
                        new
                        {
                            ProductSubcategoryID = 213,
                            ParentCategoryID = 2,
                            ProductSubcategoryDescription = "Plasmid Purification"
                        },
                        new
                        {
                            ProductSubcategoryID = 301,
                            ParentCategoryID = 3,
                            ProductSubcategoryDescription = "Virus"
                        },
                        new
                        {
                            ProductSubcategoryID = 302,
                            ParentCategoryID = 3,
                            ProductSubcategoryDescription = "Plasmid"
                        },
                        new
                        {
                            ProductSubcategoryID = 303,
                            ParentCategoryID = 3,
                            ProductSubcategoryDescription = "Primers"
                        },
                        new
                        {
                            ProductSubcategoryID = 304,
                            ParentCategoryID = 3,
                            ProductSubcategoryDescription = "Probes"
                        },
                        new
                        {
                            ProductSubcategoryID = 401,
                            ParentCategoryID = 4,
                            ProductSubcategoryDescription = "Beaker"
                        },
                        new
                        {
                            ProductSubcategoryID = 402,
                            ParentCategoryID = 4,
                            ProductSubcategoryDescription = "Measuring"
                        },
                        new
                        {
                            ProductSubcategoryID = 403,
                            ParentCategoryID = 4,
                            ProductSubcategoryDescription = "Tube Holders"
                        },
                        new
                        {
                            ProductSubcategoryID = 404,
                            ParentCategoryID = 4,
                            ProductSubcategoryDescription = "Buckets"
                        },
                        new
                        {
                            ProductSubcategoryID = 405,
                            ParentCategoryID = 4,
                            ProductSubcategoryDescription = "Cooling Racks"
                        },
                        new
                        {
                            ProductSubcategoryID = 406,
                            ParentCategoryID = 4,
                            ProductSubcategoryDescription = "-196 Box"
                        },
                        new
                        {
                            ProductSubcategoryID = 407,
                            ParentCategoryID = 4,
                            ProductSubcategoryDescription = "-80 Box"
                        },
                        new
                        {
                            ProductSubcategoryID = 501,
                            ParentCategoryID = 5,
                            ProductSubcategoryDescription = "Instrument"
                        },
                        new
                        {
                            ProductSubcategoryID = 502,
                            ParentCategoryID = 5,
                            ProductSubcategoryDescription = "Instrument Parts"
                        },
                        new
                        {
                            ProductSubcategoryID = 503,
                            ParentCategoryID = 5,
                            ProductSubcategoryDescription = "Instrument Check"
                        },
                        new
                        {
                            ProductSubcategoryID = 504,
                            ParentCategoryID = 5,
                            ProductSubcategoryDescription = "Instrument Fixing"
                        },
                        new
                        {
                            ProductSubcategoryID = 505,
                            ParentCategoryID = 5,
                            ProductSubcategoryDescription = "Instrument Calibration"
                        },
                        new
                        {
                            ProductSubcategoryID = 506,
                            ParentCategoryID = 5,
                            ProductSubcategoryDescription = "Instrument Warranty"
                        },
                        new
                        {
                            ProductSubcategoryID = 507,
                            ParentCategoryID = 5,
                            ProductSubcategoryDescription = "Lab Software"
                        },
                        new
                        {
                            ProductSubcategoryID = 508,
                            ParentCategoryID = 5,
                            ProductSubcategoryDescription = "Lab Furniture"
                        },
                        new
                        {
                            ProductSubcategoryID = 601,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Computer"
                        },
                        new
                        {
                            ProductSubcategoryID = 602,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Rent"
                        },
                        new
                        {
                            ProductSubcategoryID = 603,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Communication"
                        },
                        new
                        {
                            ProductSubcategoryID = 604,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Branding"
                        },
                        new
                        {
                            ProductSubcategoryID = 605,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Travel"
                        },
                        new
                        {
                            ProductSubcategoryID = 606,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Shipment"
                        },
                        new
                        {
                            ProductSubcategoryID = 607,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Transportation"
                        },
                        new
                        {
                            ProductSubcategoryID = 608,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Rennovation"
                        },
                        new
                        {
                            ProductSubcategoryID = 609,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Bookkeeping"
                        },
                        new
                        {
                            ProductSubcategoryID = 610,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Law Advisement"
                        },
                        new
                        {
                            ProductSubcategoryID = 611,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Tax"
                        },
                        new
                        {
                            ProductSubcategoryID = 612,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Books And Journal"
                        },
                        new
                        {
                            ProductSubcategoryID = 613,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Regulations"
                        },
                        new
                        {
                            ProductSubcategoryID = 614,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Clinical Regulation"
                        },
                        new
                        {
                            ProductSubcategoryID = 615,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Conference"
                        },
                        new
                        {
                            ProductSubcategoryID = 616,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Company Events"
                        },
                        new
                        {
                            ProductSubcategoryID = 617,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Insurance"
                        },
                        new
                        {
                            ProductSubcategoryID = 618,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "General"
                        },
                        new
                        {
                            ProductSubcategoryID = 619,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Software"
                        },
                        new
                        {
                            ProductSubcategoryID = 620,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Hotels"
                        },
                        new
                        {
                            ProductSubcategoryID = 621,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Flight Tickets"
                        },
                        new
                        {
                            ProductSubcategoryID = 622,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Scientific Advice"
                        },
                        new
                        {
                            ProductSubcategoryID = 623,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Brokerage"
                        },
                        new
                        {
                            ProductSubcategoryID = 624,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Business Advice"
                        },
                        new
                        {
                            ProductSubcategoryID = 625,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Electric Appliances"
                        },
                        new
                        {
                            ProductSubcategoryID = 626,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Safety"
                        },
                        new
                        {
                            ProductSubcategoryID = 627,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Food"
                        },
                        new
                        {
                            ProductSubcategoryID = 628,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Stationary"
                        },
                        new
                        {
                            ProductSubcategoryID = 629,
                            ParentCategoryID = 6,
                            ProductSubcategoryDescription = "Furniture"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectID = 1,
                            ProjectDescription = "Rejuvenation"
                        },
                        new
                        {
                            ProjectID = 2,
                            ProjectDescription = "Delivery Systems"
                        },
                        new
                        {
                            ProjectID = 3,
                            ProjectDescription = "Biomarkers"
                        },
                        new
                        {
                            ProjectID = 4,
                            ProjectDescription = "Clinical Trials"
                        },
                        new
                        {
                            ProjectID = 5,
                            ProjectDescription = "General"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Request", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AmountWithInLocation")
                        .HasColumnType("bigint");

                    b.Property<long?>("AmountWithOutLocation")
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserReceiverID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CatalogNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateToBePaid")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<double>("ExchangeRate")
                        .HasColumnType("float");

                    b.Property<byte>("ExpectedSupplyDays")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ParentRequestID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestStatusID")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubProjectID")
                        .HasColumnType("int");

                    b.Property<long?>("SubSubUnit")
                        .HasColumnType("bigint");

                    b.Property<int?>("SubSubUnitTypeID")
                        .HasColumnType("int");

                    b.Property<long?>("SubUnit")
                        .HasColumnType("bigint");

                    b.Property<int?>("SubUnitTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("Terms")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Unit")
                        .HasColumnType("bigint");

                    b.Property<int?>("UnitTypeID")
                        .HasColumnType("int");

                    b.Property<long>("UnitsInStock")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitsOrdered")
                        .HasColumnType("bigint");

                    b.Property<byte>("Warranty")
                        .HasColumnType("tinyint");

                    b.HasKey("RequestID");

                    b.HasIndex("ApplicationUserReceiverID");

                    b.HasIndex("ParentRequestID");

                    b.HasIndex("ProductID");

                    b.HasIndex("RequestStatusID");

                    b.HasIndex("SubProjectID");

                    b.HasIndex("SubSubUnitTypeID");

                    b.HasIndex("SubUnitTypeID");

                    b.HasIndex("UnitTypeID");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.RequestLocationInstance", b =>
                {
                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<int>("LocationInstanceID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ParentLocationInstanceID")
                        .HasColumnType("int");

                    b.HasKey("RequestID", "LocationInstanceID");

                    b.HasIndex("LocationInstanceID");

                    b.HasIndex("ParentLocationInstanceID");

                    b.ToTable("RequestLocationInstance");
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.RequestStatus", b =>
                {
                    b.Property<int>("RequestStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RequestStatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestStatusID");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            RequestStatusID = 1,
                            RequestStatusDescription = "New"
                        },
                        new
                        {
                            RequestStatusID = 2,
                            RequestStatusDescription = "Ordered"
                        },
                        new
                        {
                            RequestStatusID = 3,
                            RequestStatusDescription = "RecievedAndIsInventory"
                        },
                        new
                        {
                            RequestStatusID = 4,
                            RequestStatusDescription = "Partial"
                        },
                        new
                        {
                            RequestStatusID = 5,
                            RequestStatusDescription = "Clarify"
                        },
                        new
                        {
                            RequestStatusID = 6,
                            RequestStatusDescription = "PayNow"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.SubProject", b =>
                {
                    b.Property<int>("SubProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("SubProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubProjectID");

                    b.HasIndex("ProjectID");

                    b.ToTable("SubProjects");

                    b.HasData(
                        new
                        {
                            SubProjectID = 101,
                            ProjectID = 1,
                            SubProjectDescription = "Epigenetic Rejuvenation"
                        },
                        new
                        {
                            SubProjectID = 102,
                            ProjectID = 1,
                            SubProjectDescription = "Plasma Rejuvenation"
                        },
                        new
                        {
                            SubProjectID = 201,
                            ProjectID = 2,
                            SubProjectDescription = "AAV"
                        },
                        new
                        {
                            SubProjectID = 301,
                            ProjectID = 3,
                            SubProjectDescription = "Epigenetic Clock"
                        },
                        new
                        {
                            SubProjectID = 302,
                            ProjectID = 3,
                            SubProjectDescription = "Telomere Measurement"
                        },
                        new
                        {
                            SubProjectID = 401,
                            ProjectID = 4,
                            SubProjectDescription = "Biomarker Trial"
                        },
                        new
                        {
                            SubProjectID = 501,
                            ProjectID = 5,
                            SubProjectDescription = "General"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.UnitParentType", b =>
                {
                    b.Property<int>("UnitParentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UnitParentTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitParentTypeID");

                    b.ToTable("UnitParentTypes");

                    b.HasData(
                        new
                        {
                            UnitParentTypeID = 1,
                            UnitParentTypeDescription = "Units"
                        },
                        new
                        {
                            UnitParentTypeID = 2,
                            UnitParentTypeDescription = "Weight/Volume"
                        },
                        new
                        {
                            UnitParentTypeID = 3,
                            UnitParentTypeDescription = "Test"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.UnitType", b =>
                {
                    b.Property<int>("UnitTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UnitParentTypeID")
                        .HasColumnType("int");

                    b.Property<string>("UnitTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitTypeID");

                    b.HasIndex("UnitParentTypeID");

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            UnitTypeID = 1,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Bottle"
                        },
                        new
                        {
                            UnitTypeID = 2,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Box"
                        },
                        new
                        {
                            UnitTypeID = 3,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Pack"
                        },
                        new
                        {
                            UnitTypeID = 4,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Bag"
                        },
                        new
                        {
                            UnitTypeID = 5,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Unit"
                        },
                        new
                        {
                            UnitTypeID = 6,
                            UnitParentTypeID = 1,
                            UnitTypeDescription = "Vial"
                        },
                        new
                        {
                            UnitTypeID = 7,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "Kg"
                        },
                        new
                        {
                            UnitTypeID = 8,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "gr"
                        },
                        new
                        {
                            UnitTypeID = 9,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "mg"
                        },
                        new
                        {
                            UnitTypeID = 10,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "ug"
                        },
                        new
                        {
                            UnitTypeID = 11,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "Liter"
                        },
                        new
                        {
                            UnitTypeID = 12,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "ml"
                        },
                        new
                        {
                            UnitTypeID = 13,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "ul"
                        },
                        new
                        {
                            UnitTypeID = 14,
                            UnitParentTypeID = 2,
                            UnitTypeDescription = "gal"
                        },
                        new
                        {
                            UnitTypeID = 15,
                            UnitParentTypeID = 3,
                            UnitTypeDescription = "rxhs"
                        },
                        new
                        {
                            UnitTypeID = 16,
                            UnitParentTypeID = 3,
                            UnitTypeDescription = "test"
                        },
                        new
                        {
                            UnitTypeID = 17,
                            UnitParentTypeID = 3,
                            UnitTypeDescription = "preps"
                        },
                        new
                        {
                            UnitTypeID = 18,
                            UnitParentTypeID = 3,
                            UnitTypeDescription = "assays"
                        });
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Vendor", b =>
                {
                    b.Property<int>("VendorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("OrderEmail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorAccountNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorBIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorBank")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorBankBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.Property<string>("VendorBuisnessID")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)")
                        .HasMaxLength(9);

                    b.Property<string>("VendorCity")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorContactPhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorContactPhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorEnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorGoldAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorHeName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorStreet")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VendorSwift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorZip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorID");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Comment", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.CompanyAccount", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.LocationInstance", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.LocationInstance", "LocationInstanceParent")
                        .WithMany()
                        .HasForeignKey("LocationInstanceParentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.LocationType", "LocationType")
                        .WithMany()
                        .HasForeignKey("LocationTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.LocationType", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.LocationType", "LocationTypeChild")
                        .WithMany()
                        .HasForeignKey("LocationTypeChildID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.LocationType", "LocationTypeParent")
                        .WithMany()
                        .HasForeignKey("LocationTypeParentID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.ParentRequest", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("ParentRequests")
                        .HasForeignKey("ApplicationUserID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Payment", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.CompanyAccount", "CompanyAccount")
                        .WithMany()
                        .HasForeignKey("CompanyAccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Models.ParentRequest", "ParentRequest")
                        .WithMany("Payments")
                        .HasForeignKey("ParentRequestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Product", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.ProductSubcategory", "ProductSubcategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductSubcategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Models.Vendor", "Vendor")
                        .WithMany("Products")
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.ProductSubcategory", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.ParentCategory", "ParentCategory")
                        .WithMany("ProductSubcategories")
                        .HasForeignKey("ParentCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.Request", b =>
                {
                    b.HasOne("PrototypeWithAuth.Data.ApplicationUser", "ApplicationUserReceiver")
                        .WithMany()
                        .HasForeignKey("ApplicationUserReceiverID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.ParentRequest", "ParentRequest")
                        .WithMany("Requests")
                        .HasForeignKey("ParentRequestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Models.Product", "Product")
                        .WithMany("Requests")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Models.RequestStatus", "RequestStatus")
                        .WithMany("Requests")
                        .HasForeignKey("RequestStatusID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.SubProject", "SubProject")
                        .WithMany("Requests")
                        .HasForeignKey("SubProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Models.UnitType", "SubSubUnitType")
                        .WithMany()
                        .HasForeignKey("SubSubUnitTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.UnitType", "SubUnitType")
                        .WithMany()
                        .HasForeignKey("SubUnitTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrototypeWithAuth.Models.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.RequestLocationInstance", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.LocationInstance", "LocationInstance")
                        .WithMany("RequestLocationInstances")
                        .HasForeignKey("LocationInstanceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Models.LocationInstance", "ParentLocationInstance")
                        .WithMany("AllRequestLocationInstances")
                        .HasForeignKey("ParentLocationInstanceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrototypeWithAuth.Models.Request", "Request")
                        .WithMany("RequestLocationInstances")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.SubProject", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.Project", "Project")
                        .WithMany("SubProjects")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrototypeWithAuth.Models.UnitType", b =>
                {
                    b.HasOne("PrototypeWithAuth.Models.UnitParentType", "UnitParentType")
                        .WithMany("UnitTypes")
                        .HasForeignKey("UnitParentTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
