//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.LocationModels {
    using System;
    using System.Linq;
    using System.Text;
    using System.ComponentModel.DataAnnotations;
    
    
    [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.ComponentModel.DataAnnotations.KeyAttribute))]
    public class closet {
        
        public int closetID { get; set; } //;
        
        public string shelf { get; set; } //;
    }
}
